# Generated by Django 3.2.3 on 2021-05-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('idMaquina', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de maquina')),
                ('marcaMaquina', models.CharField(max_length=50, verbose_name='Nombre de la maquina')),
                ('modeloMaquina', models.CharField(max_length=50, verbose_name='Modelo de la maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('idRepuesto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de repuesto')),
                ('nombreRepuesto', models.CharField(max_length=20, verbose_name='Nombre repuesto')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.maquina')),
            ],
        ),
    ]
