# Generated by Django 3.2.3 on 2021-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de servicio')),
                ('nombreServicio', models.CharField(max_length=25, verbose_name='Nombre servicio')),
                ('descripcionServicio', models.CharField(max_length=120, verbose_name='Nombre servicio')),
            ],
        ),
    ]
